### ISSUE TITLE
After importing into unity

### ISSUE THREAD

**Issue by YouriOkkerse** [nol1fe/delaunator-sharp#10]
Library\PackageCache\com.nol1fe.delaunator@d542c6bf57\Runtime\Scripts\UniformPoissionDiskSampler.cs(176,30): error CS0723: Cannot declare a variable of static type 'Random'

**Comment by TylerKostuch** [comment]
After upgrading to Unity 2020.20f1, I am seeing this error as well.

**Comment by YouriOkkerse** [comment]
I believe you can leave out the entire line and the error is resolved. Since I have been working on so many different projects the past days I can't perfectly recall but I believe the line was unused. Furthermore a really nice package.

**Comment by TylerKostuch** [comment]
Yeah, looking at the code, I'm not sure why Random was an instance in the first place.

As this [documentation outlines](https://docs.unity3d.com/2020.2/Documentation/ScriptReference/Random.html), `UnityEngine.Random` _is_ a static class in both 2019.3 and 2020.2.

Removing [line 176](https://github.com/nol1fe/delaunator-sharp/blob/6a6eabf721820f44fe9cb7ec82bd2f92a7cd67a9/DelaunatorSharp.Unity/Runtime/Scripts/UniformPoissionDiskSampler.cs#L176) should not impact the other Random calls, as it will now just access the static version.

I'm going to go ahead and work with that for a while and see if any issues arise.

**Comment by nol1fe** [comment]
Hi,

@TylerKostuch, @YouriOkkerse  you are both correct, this line should not exists over there at all. 
It was transfered from System.Random implementation and i've made some copy-paste error.
Sorry for troubles :) 

I've pushed an update and now everything seems to be alright. 

Cheers

**Comment by TylerKostuch** [comment]
Thanks @YouriOkkerse, I hate maintain a fork so I appreciate the fast update. Everything is working perfectly.
