### ISSUE TITLE
How to use it if I have a Vector2D array

### ISSUE THREAD

**Issue by lelouch0204** [nol1fe/delaunator-sharp#11]
Hi, sorry if this is a very noob question, but I could not figure out a way to generate triangulations if I have a Vector2D array, how should I be approaching this? Thanks in advance?

**Comment by nol1fe** [comment]
Hello @lelouch0204 

There are multiplay ways to achieve that. 
If you are using it inside Unity and Vector2d comes from UnityEngine namespace you can just use   [extensions](https://github.com/nol1fe/delaunator-sharp?path=DelaunatorSharp.Unity/Runtime/Scripts/DelaunatorExtensions.cs) from example

The most simple way is to select from your array DelaunatorSharp Point that is already implementing IPoint interface

```
var points = yourArray.Select(point => new DelaunatorSharp.Point(point.X, point.Y));
var delaunator = new Delaunator(points);

delaunator.ForEachTriangleEdge(edge =>
{
         // your draw line method
         DrawLine(edge.P, edge.Q);
});
```

Explore samples in repository and visit https://mapbox.github.io/delaunator/ for more information.

Cheers

**Comment by lelouch0204** [comment]
Thanks a lot for the help man, really appreciate it!!
