### ISSUE TITLE
Border points seem to generate wrong cells?

### ISSUE THREAD

**Issue by codewing** [nol1fe/delaunator-sharp#14]
I'm having issues when it comes to the generation of the cells. 
While the inner points seem to work fine the outer points are causing trouble.
(generate with the GetVoronoiCellsBasedOnCentroids() command)

![Inkedvoronoi_tmp_LI](https://user-images.githubusercontent.com/12066466/110820793-b7c4e300-828f-11eb-8b75-b3998501730e.jpg)

I've added the points to the ticket
[points.txt](https://github.com/nol1fe/delaunator-sharp/files/6124463/points.txt)

**Comment by codewing** [comment]
This is with GetVoronoiCellsBasedOnCircumcenters
Especially 4 looks interesting
![Inkedvoronoi_tmp_L2I](https://user-images.githubusercontent.com/12066466/110821075-04a8b980-8290-11eb-8821-8bcd830b3eed.jpg)
[points.txt](https://github.com/nol1fe/delaunator-sharp/files/6124537/points.txt)

**Comment by nol1fe** [comment]
Hello @codewing
This is the limitation described in this [article](https://mapbox.github.io/delaunator/) under the Convex Hull Section. Unfortunately I can't help you with this.

Cheers

**Comment by codewing** [comment]
Ah sorry that I skipped over that...
