### ISSUE TITLE
Triangulation by Ear Clipping

### ISSUE THREAD

**Issue by ThanbirTamim** [nol1fe/delaunator-sharp#16]
After providing set of points, I had been getting this output but how to clip those edges??

![Screenshot (81)](https://user-images.githubusercontent.com/37415870/140874051-88a78c86-46d9-4d95-93af-7fdb1c2737e2.png)
![Screenshot (80)](https://user-images.githubusercontent.com/37415870/140874078-4b2a07f3-66d6-4427-8802-eb06e150117d.png)

**Comment by nol1fe** [comment]
Hello @ThanbirTamim,
Unfortunately Delaunator does not support it. Visit this [thread](https://github.com/nol1fe/delaunator-sharp/issues/8) for more info.

Cheers

**Comment by ThanbirTamim** [comment]
> Hello @ThanbirTamim, Unfortunately Delaunator does not support it. Visit this [thread](https://github.com/nol1fe/delaunator-sharp/issues/8) for more info.
> 
> Cheers
Acknowledged. Thank you dear.
