### ISSUE TITLE
Large numbers of errors when importing into Unity

### ISSUE THREAD

**Issue by ElnuDev** [nol1fe/delaunator-sharp#2]
When importing the repo into Unity, I get dozens of errors, most of which say that there are namespaces that cannot be found or duplicate attributes. Any thoughts on fixing this? Are there some requirements for using this library that I'm not aware of? Thank you in advance!

**Comment by nol1fe** [comment]
@ElnuDev
I've made the update of repository.  
Visit the [Installation section ](https://github.com/nol1fe/delaunator-sharp#unity-installation) in readme file for details how to import package into Unity. 

Cheers

**Comment by nol1fe** [comment]
Hi @ElnuDev
Sorry for the late response!

Visit the [Installation section ](https://github.com/nol1fe/delaunator-sharp#unity-installation) in readme file for the details on how to import package into Unity. 

Cheers
