### ISSUE TITLE
 Enhancing `delaunator-sharp` with `BurstTriangulator`

### ISSUE THREAD

**Issue by andywiecko** [nol1fe/delaunator-sharp#22]
Hi,

I recently came across [`delaunator-sharp`][delaunator-sharp] and wanted to express my admiration for your excellent work in porting [`delaunator`][delaunator]!

I also have a project related to triangulation called [`BurstTriangulator`][burst-triangulator]. Upon discovering [`delaunator-sharp`][delaunator-sharp], I decided to replace my previous algorithm, which was based on the Bower-Watson algorithm, with this "half-edges" approach. The performance improvement was truly remarkable!

I conducted a benchmark comparing [`delaunator-sharp`][delaunator-sharp] with my [`BurstTriangulator`][burst-triangulator], and since I utilize `Burst`, I observed a significant speedup in my package. However, there is still room for additional performance enhancements.

![image](https://github.com/nol1fe/delaunator-sharp/assets/15237586/3d760dc5-a70f-4ddf-8d8b-51885afff888)

In addition to classical triangulation, my package offers constrained triangulation and triangulation with mesh refinement. Currently, the project is primarily designed for Unity projects due to its dependency on `Burst`.

If you are interested, I invite you to mention my project in your `README.md`. I believe that Unity users would greatly appreciate having a reference to a related project.

Best regards, 
Andrzej Więckowski

[delaunator]: https://github.com/mapbox/delaunator
[delaunator-sharp]: https://github.com/nol1fe/delaunator-sharp
[burst-triangulator]: https://github.com/andywiecko/BurstTriangulator

**Comment by nol1fe** [comment]
Dear @andywiecko,

Thank you for your kind words and for reaching out! I'm thrilled to hear that you found delaunator-sharp helpful in your project. It's always great to see developers like you finding innovative ways to improve upon existing algorithms and push the boundaries of what's possible. BurstTriangulator has been added to our README.md as you suggested.

Let's keep making great things happen!

**Comment by andywiecko** [comment]
Great, I really appreciate it!

As a side note, I've been putting in a lot of work recently, and I'm planning to release `v3` latter this month with additional performance and quality improvements.
