### ISSUE TITLE
One point is not used in the Delaunay triangulation

### ISSUE THREAD

**Issue by ghostelet** [nol1fe/delaunator-sharp#3]
Hi,

I'm facing this strange issue where one of the points I give in input for the triangulation ends up not being used. Usually it happens when there's more than 100 points used for the triangulation. I don't see any obvious pattern on why the point is not used (the point could be located roughly in the middle or on the edges, doesn't matter). For example if you use the code below with the list of points in attachment, you will see that the point ID 29 is not used. But actually, you could use pretty much any randomly generated list of (> 100) points and the same would happen.

```C#
System.IO.File.ReadAllText("points.txt")
    .Split(new string[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries)
    .Select(l => l.Split(new char[] { ',' })).Select(c => new Point(double.Parse(c[0]), double.Parse(c[1])));
var triangulation = new Delaunator(points);
var usedPoints = triangulation.Triangles.Distinct().OrderBy(_ => _).ToList();
```
[points.txt](https://github.com/nol1fe/delaunator-sharp/files/4908221/points.txt)

**Comment by nol1fe** [comment]
Hi @ghostelet,
Sorry for the late response!

You have to make sure that the list of points you have provided is distincted.
In your file "points.txt" there is point 44.6484375,10.8984375 that exists two times.

To find doubles you can use this sample of code.
 
```
  var points= File.ReadAllText("points.txt")
                            .Split(new string[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries)
                            .Select(l => l.Split(new char[] { ',' }))
                            .Select(c => new Point(double.Parse(c[0]) * 10, double.Parse(c[1]) * 10))
                            .OfType<IPoint>()
                            .GroupBy(x => x)
                            .Where(x => x.Count() > 1)
                            .ToList();
```

Cheers

**Comment by ghostelet** [comment]
Yeah, indeed it looks like it's the way I was generating the points that had some issues. I had checked for duplicates but only on the point causing issues. Thanks!
