### ISSUE TITLE
Infinite loop in Legalize with some inputs

### ISSUE THREAD

**Issue by matthewfender** [nol1fe/delaunator-sharp#4]
I have some test points that result in an infinite loop during a call to Legalize. The issue in particular seems to be on line 363, where you call e = hullNext[e]; meaning that the do/while (e != hullStart) loop is never exited. Cross-referencing to the original delaunator project, and it looks like a typo when rewriting in c#; the original loop assigns e = hullPrev[e]. I can confirm that changing this seems to fix the issue for me.

**Comment by nol1fe** [comment]
Hi @matthewfender
You are correct. Thanks for reporting the issue.
I've updated the package.

Cheers
