### ISSUE TITLE
Q: does it support holes? 

### ISSUE THREAD

**Issue by jhm-ciberman** [nol1fe/delaunator-sharp#8]
I am developing a procedurally generated mesh for a house wall with a window in Unity. 
I have a set of convex coplanar points (the window outline) and I want to carve a hole in a 3D flat rectangle (the wall). The hard part is the triangulation of course. Does this library support holes? 

Edit: maybe I am bad at reading the documentation, but it seems it does not support holes. Maybe is there an easy way to add this feature?

**Comment by nol1fe** [comment]
Hello @jhm-ciberman,
Unfortunately Delaunator does not support boolean operations, holes, constraints or conforms.

Visit this [thread](https://github.com/mapbox/delaunator/issues/9), maybe you'll find something usefull over there.

By the way, if you are into procedural generation, give Houdini from SideFX a try. It's really great piece of software.

Cheers

**Comment by jhm-ciberman** [comment]
Hi @nol1fe 
Thank you for your answer. I spent yesterday reading about Delaunay triangulation and constrained triangulation, and now I understand the difference. I think I will use https://github.com/SebLague/Ear-Clipping-Triangulation for my project. Thanks anyway for your time!
